# Generated by Django 4.1.2 on 2024-10-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='instrest',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='received_from',
            field=models.CharField(default='Kari sir', max_length=250),
            preserve_default=False,
        ),
    ]
